Feature branch
chidiebereojingwa/conference-page pull request #1
Opened 2022-03-18 09:16 UTC by chidiebereojingwa

## EASYSEND International conference website

This page was built with :
- HTML
- CSS
- JS
## Demo video
https://www.loom.com/share/f94afff958e04e36809b8c0d1382fc79

2022-03-18 12:12 UTC, FrederickMih requested changes
Hi @chidiebereojingwa , 

Your project is amazing!
Congratulations on your achievements so far :+1: 
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
![](https://media.giphy.com/media/eJiVOyCoU0EWrWJAAt/giphy.gif)

 > #  To Highlights :rocket: 

- Your linters are properly configured and passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark: 


## Suggested changes

- [ ] Hi @chidiebereojingwa, so far you have done a great job recording a video presentation of your project. :+1: . To improve on the presentation, kingly records another video making the topic and the purpose of your project clearer. The video should also contain a highlight about a piece of code you found interesting or proud of making.
- [ ] Please let's also make each section of our page active when click it to show that we are currently viewing that section. For example, when I click on the **About** link, this link should turn active(red in color), I believe you can do this :pray: 

_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-18 12:12 UTC, FrederickMih commented on index.html
> +      </li>
- [ ] Great job on working on your mobile nav menu. What do you think of getting rid of this logo amongst the mobile menu options?. It doesn't look presentable here
![annotely_image](https://user-images.githubusercontent.com/63087491/158986663-3b50a76c-cdb1-47ee-ac66-12ad349d2b18.png)
.

2022-03-18 12:12 UTC, FrederickMih commented on index.html
> +  </nav>
- [ ] On the desktop size, let's make sure that this taller section of the navbar is in line with the top dark bar section. Check screenshots below:
- **Original design**
![original](https://user-images.githubusercontent.com/63087491/159007295-fa8e2eb8-6e7a-49b7-b121-934491954759.png)


- **Your design**
![annotely_image](https://user-images.githubusercontent.com/63087491/158988382-c3f0319d-48b2-48bd-a42a-efefe49a515a.png)

2022-03-18 12:12 UTC, FrederickMih commented on about.html
> +    </footer>
- [ ] Please let's make the background(about page) of the footer dark as seen in the original design. From the requirements of this project, we are expected to have a dark background.

2022-03-18 12:12 UTC, FrederickMih commented on index.html
> +  </section>
- [ ] Please let's work a little bit on the design of this section. The subtitles of the original design do not contain an underline, and there's a second light image behind the main image. For more information, check out the screenshots below: 
- **Original design**
![Screenshot from 2022-03-18 11-53-24](https://user-images.githubusercontent.com/63087491/158991510-eb6f1c71-3ced-4750-964c-d0935dc4a05e.png)

- **Your design**
![Screenshot from 2022-03-18 11-52-51](https://user-images.githubusercontent.com/63087491/158991614-f915ad72-c4c7-45fd-9813-411b12100182.png)

2022-03-18 12:12 UTC, FrederickMih commented on about.html
> +      <hr class="header-hr">
- [ ] What do you think of getting rid of this underline?. Remember we are expected to follow [this](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) design but must personalize the content

2022-03-18 12:12 UTC, FrederickMih commented on about.html
> +    </header>
- [ ] Hi @chidiebereojingwa, remember this is not a header but a section of your page. Please let's make this a section for semantic reasons.

2022-03-18 12:12 UTC, FrederickMih commented on about.html
> +    </header>
- [ ] This very top section should include a page title, a block with a page description, and a line with contact information. If you take a look keenly at your design, you will discover that you have replaced the contact section with a section from the home page. Please check out the original design and work more on this. These sections are not the same.

2022-03-18 12:12 UTC, FrederickMih commented on about.html
> +      </div>
- [ ] In this bottom section of the about page, these texts should be centered over two images. Check screenshots below:
- **Original**
![Screenshot from 2022-03-18 12-39-36](https://user-images.githubusercontent.com/63087491/158996839-9849264c-542a-49a2-8765-b41738ff5541.png)

- **Yours**
![Screenshot from 2022-03-18 12-39-05](https://user-images.githubusercontent.com/63087491/158996903-b15760e0-4165-4d57-a6d8-2077e8b11dc6.png)

So we needs background images

2022-03-18 12:12 UTC, FrederickMih commented on about.html
> +    </section>
- [ ] Please we don't need this partner section on the about page.

2022-03-18 12:12 UTC, FrederickMih commented on index.html
> +  </header>
- [ ] Please this is not a header but a section on your main page. Let's make it a section for [semantic reasons](https://developer.mozilla.org/en-US/docs/Glossary/Semantics).

2022-03-18 12:12 UTC, FrederickMih commented on index.html
> +      </div>
- [ ] Remember this is an article. It will be better for us to make use of the semantic `article` element instead of your generic `div` element. What do you think?. Please don't forget to do the same for all the articles on this page.

2022-03-18 12:12 UTC, FrederickMih commented on css/style.css
> +}
- [ ] Please always make sure that media queries should be organized at the button of the stylesheet, that will save you from stress of using important! everytime.. Therefore let's move these codes above the media queries.

2022-03-19 00:30 UTC, chidiebereojingwa commented on about.html
> +      <hr class="header-hr">
Please check the design again

2022-03-19 00:36 UTC, chidiebereojingwa commented on about.html
> +    </header>
It is a header

2022-03-19 00:48 UTC, chidiebereojingwa commented on index.html
> +  </header>
Please this is a header

2022-03-19 01:44 UTC, micheaol requested changes
Hi @chidiebereojingwa , 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

 ## Required Changes ♻️

- _Check the comments under the review._
- As requested by the previous code reviewer, to improve on the presentation, kingly records another video making the topic and the purpose of your project clearer. The video should also contain a highlight about a piece of code you found interesting or proud of making.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-19 01:44 UTC, micheaol commented on index.html
> +      </div>
As requested by the previous code reviewer,  kindly include the second light image behind the main image.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/159101730-915522d8-9fef-4f18-92d2-cd46e93e30a3.png) | ![image](https://user-images.githubusercontent.com/10332499/159101751-4ae417f4-3b4e-4a9e-b238-29f2f18f44a6.png)

2022-03-19 01:44 UTC, micheaol commented on about.html
> +      </div>
As requested by the previous code reviewer, kindly add background images to this section according to the requirement.

> * [ ]  In this bottom section of the about page, these texts should be centered over two images. Check screenshots below:
> * **Original**
>   ![Screenshot from 2022-03-18 12-39-36](https://user-images.githubusercontent.com/63087491/158996839-9849264c-542a-49a2-8765-b41738ff5541.png)
> * **Yours**
>   ![Screenshot from 2022-03-18 12-39-05](https://user-images.githubusercontent.com/63087491/158996903-b15760e0-4165-4d57-a6d8-2077e8b11dc6.png)
> 
> So we needs background images

2022-03-19 08:24 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 08:25 UTC, merged